remove request_fragment_check.py
using `request_fragment_check.py` requires the lxplus env

```
env: 'cern-get-sso-cookie': No such file or directory
Traceback (most recent call last):
  File "./request_fragment_check.py", line 16, in <module>
    from rest3 import McM
ModuleNotFoundError: No module named 'rest3'
GEN Checking Script returned exit code 1 which means there are 1 errors
Validation WILL NOT RUN
Please correct errors in the request and run validation again
```